// Command nervctl is the Nerv CLI: generate registered, templated
// projects backed by the registry, template engine, dependency
// resolver, CI hook, and metrics packages.
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"time"

	"tazzledazzle/nerv/nerv/internal/cihook"
	"tazzledazzle/nerv/nerv/internal/depgraph"
	"tazzledazzle/nerv/nerv/internal/metrics"
	"tazzledazzle/nerv/nerv/internal/registry"
	"tazzledazzle/nerv/nerv/internal/template"
)

// app bundles every wired-up component nervctl commands operate on.
type app struct {
	reg      registry.Registrar
	engine   *template.Engine
	resolver *depgraph.Resolver
	hook     cihook.CIHook
	metrics  *metrics.Metrics
}

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(1)
	}

	dataDir := os.Getenv("NERV_DATA_DIR")
	if dataDir == "" {
		dataDir = "./.nerv-data"
	}
	if err := os.MkdirAll(dataDir, 0o755); err != nil {
		log.Fatalf("nervctl: creating data dir %q: %v", dataDir, err)
	}

	a, closeFn, err := buildApp(dataDir)
	if err != nil {
		log.Fatalf("nervctl: %v", err)
	}
	defer closeFn()

	switch os.Args[1] {
	case "new":
		a.cmdNew(os.Args[2:])
	case "list":
		a.cmdList(os.Args[2:])
	case "serve-metrics":
		a.cmdServeMetrics(os.Args[2:])
	default:
		usage()
		os.Exit(1)
	}
}

func usage() {
	fmt.Println(`nervctl — Nerv project generator CLI

Usage:
  nervctl new --lang=<language> --name=<project-name> [--dest=<dir>]
  nervctl list [--lang=<language>]
  nervctl serve-metrics [--addr=:9090]`)
}

// buildApp wires every package into a working app instance, backed by
// two BoltDB files under dataDir. Returns a close function that shuts
// down every store cleanly.
func buildApp(dataDir string) (*app, func(), error) {
	reg, err := registry.NewBoltStore(filepath.Join(dataDir, "registry.db"))
	if err != nil {
		return nil, nil, fmt.Errorf("building registry: %w", err)
	}

	pointers, err := template.NewBoltPointerStore(filepath.Join(dataDir, "pointers.db"))
	if err != nil {
		_ = reg.Close()
		return nil, nil, fmt.Errorf("building pointer store: %w", err)
	}

	catalog := template.NewMemCatalog()
	seedBuiltinTemplates(catalog)
	if err := pointers.SetCurrent("service", "v1"); err != nil {
		_ = reg.Close()
		_ = pointers.Close()
		return nil, nil, fmt.Errorf("seeding template pointer: %w", err)
	}

	engine := template.NewEngine(catalog, pointers)
	resolver := depgraph.NewResolver(depgraph.NewEnforcer(depgraph.Policy{}), depgraph.NewCache())
	hook := cihook.NewStubHook()
	m := metrics.New()

	a := &app{reg: reg, engine: engine, resolver: resolver, hook: hook, metrics: m}

	closeFn := func() {
		if err := reg.Close(); err != nil {
			log.Printf("nervctl: closing registry: %v", err)
		}
		if err := pointers.Close(); err != nil {
			log.Printf("nervctl: closing pointer store: %v", err)
		}
	}

	return a, closeFn, nil
}

// seedBuiltinTemplates registers a minimal "service" template version so
// `nervctl new` works out of the box.
func seedBuiltinTemplates(catalog *template.MemCatalog) {
	files := template.Files{
		"main.go": `package main
		
		func main() {
			println("{{.ServiceName}} starting up")
		}
		`,
		"README.md": `# {{.ServiceName}}

		Generated by Nerv.
`,
	}
	if err := catalog.RegisterVersion("service", "v1", files); err != nil {
		log.Printf("nervctl: seeding template: %v", err)
	}
}

func (a *app) cmdNew(args []string) {
	fs := newFlagSet("new")
	lang := fs.String("lang", "", "project language (required)")
	name := fs.String("name", "", "project name (required)")
	dest := fs.String("dest", "./generated", "destination directory root")
	mustParse(fs, args)

	if *lang == "" || *name == "" {
		log.Fatal("nervctl new: --lang and --name are required")
	}

	projectID := fmt.Sprintf("%s-%d", *name, time.Now().UnixNano())
	projectPath := filepath.Join(*dest, *name)

	start := time.Now()
	err := a.engine.Render("service", projectPath, map[string]interface{}{"ServiceName": *name})
	if err != nil {
		log.Fatalf("nervctl new: rendering template: %v", err)
	}
	a.metrics.ObserveRenderDuration(time.Since(start).Seconds())

	pipelineRef, err := a.hook.TriggerPipeline(projectPath, *lang)
	if err != nil {
		log.Fatalf("nervctl new: wiring CI hook: %v", err)
	}

	err = a.reg.Register(registry.Project{
		ID:              projectID,
		Name:            *name,
		Language:        *lang,
		TemplateName:    "service",
		TemplateVersion: "v1",
		Path:            projectPath,
	})
	if err != nil {
		log.Fatalf("nervctl new: registering project: %v", err)
	}
	a.metrics.RecordProjectGenerated(*lang)

	fmt.Printf("Generated project %q (id=%s)\n  path:     %s\n  pipeline: %s\n", *name, projectID, projectPath, pipelineRef)
}

func (a *app) cmdList(args []string) {
	fs := newFlagSet("list")
	lang := fs.String("lang", "", "filter by language (optional)")
	mustParse(fs, args)

	projects, err := a.reg.List(*lang)
	if err != nil {
		log.Fatalf("nervctl list: %v", err)
	}

	out, err := json.MarshalIndent(projects, "", "  ")
	if err != nil {
		log.Fatalf("nervctl list: marshaling: %v", err)
	}
	fmt.Println(string(out))
}

func (a *app) cmdServeMetrics(args []string) {
	fs := newFlagSet("serve-metrics")
	addr := fs.String("addr", ":9090", "listen address")
	mustParse(fs, args)

	http.Handle("/metrics", a.metrics.Handler())
	fmt.Printf("Serving metrics on %s/metrics\n", *addr)
	if err := http.ListenAndServe(*addr, nil); err != nil {
		log.Fatalf("nervctl serve-metrics: %v", err)
	}
}
