// Command nervctl is the Nerv CLI: generate registered, templated
// projects backed by the registry, template engine, dependency
// resolver, CI hook, and metrics packages.
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"tazzledazzle/nerv/nerv/internal/api"
	"tazzledazzle/nerv/nerv/internal/cihook"
	"tazzledazzle/nerv/nerv/internal/depgraph"
	"tazzledazzle/nerv/nerv/internal/metrics"
	"tazzledazzle/nerv/nerv/internal/registry"
	"tazzledazzle/nerv/nerv/internal/template"
	"time"
)

// app bundles every wired-up component nervctl commands operate on.
type app struct {
	reg      registry.Registrar
	engine   *template.Engine
	resolver *depgraph.Resolver
	graph    *depgraph.Graph
	hook     cihook.CIHook
	metrics  *metrics.Metrics
}

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(1)
	}

	dataDir := os.Getenv("NERV_DATA_DIR")
	if dataDir == "" {
		dataDir = "./.nerv-data"
	}
	if err := os.MkdirAll(dataDir, 0o755); err != nil {
		log.Fatalf("nervctl: creating data dir %q: %v", dataDir, err)
	}

	a, closeFn, err := buildApp(dataDir)
	if err != nil {
		log.Fatalf("nervctl: %v", err)
	}
	defer closeFn()

	switch os.Args[1] {
	case "serve":
		a.cmdServe(os.Args[2:])
	case "new":
		a.cmdNew(os.Args[2:])
	case "list":
		a.cmdList(os.Args[2:])
	case "serve-metrics":
		a.cmdServeMetrics(os.Args[2:])
	default:
		usage()
		os.Exit(1)
	}
}

func usage() {
	fmt.Println(`nervctl — Nerv project generator CLI

Usage:
  nervctl new --lang=<language> --name=<project-name> [--dest=<dir>]
  nervctl list [--lang=<language>]
  nervctl serve [--addr=:8080] [--dest=<dir>]
  nervctl serve-metrics [--addr=:9090]`)
}

// buildApp wires every package into a working app instance, backed by
// two BoltDB files under dataDir. Returns a close function that shuts
// down every store cleanly.
func buildApp(dataDir string) (*app, func(), error) {
	reg, err := registry.NewBoltStore(filepath.Join(dataDir, "registry.db"))
	if err != nil {
		return nil, nil, fmt.Errorf("building registry: %w", err)
	}

	pointers, err := template.NewBoltPointerStore(filepath.Join(dataDir, "pointers.db"))
	if err != nil {
		_ = reg.Close()
		return nil, nil, fmt.Errorf("building pointer store: %w", err)
	}

	catalog := template.NewMemCatalog()
	seedBuiltinTemplates(catalog)
	if err := pointers.SetCurrent("service", "v1"); err != nil {
		_ = reg.Close()
		_ = pointers.Close()
		return nil, nil, fmt.Errorf("seeding template pointer: %w", err)
	}

	engine := template.NewEngine(catalog, pointers)
	resolver := depgraph.NewResolver(depgraph.NewEnforcer(depgraph.Policy{}), depgraph.NewCache())
	hook := cihook.NewStubHook()
	m := metrics.New()

	a := &app{reg: reg, engine: engine, resolver: resolver, graph: depgraph.NewGraph(), hook: hook, metrics: m}

	closeFn := func() {
		if err := reg.Close(); err != nil {
			log.Printf("nervctl: closing registry: %v", err)
		}
		if err := pointers.Close(); err != nil {
			log.Printf("nervctl: closing pointer store: %v", err)
		}
	}

	return a, closeFn, nil
}

// seedBuiltinTemplates registers a minimal "service" template version so
// `nervctl new` works out of the box.
func seedBuiltinTemplates(catalog *template.MemCatalog) {
	files := template.Files{
		"main.go":   mainGoTemplate,
		"README.md": readmeTemplate,
	}
	if err := catalog.RegisterVersion("service", "v1", files); err != nil {
		log.Printf("nervctl: seeding template: %v", err)
	}
}

// Declared as package-level backtick strings (column 0) rather than
// indented inline literals, so the leading whitespace of each source
// line doesn't leak into the rendered output file.
const mainGoTemplate = `package main

func main() {
	println("{{.ServiceName}} starting up")
}
`

const readmeTemplate = `# {{.ServiceName}}

Generated by Nerv.
`

func (a *app) cmdServe(args []string) {
	fs := newFlagSet("serve")
	addr := fs.String("addr", ":8080", "listen address")
	dest := fs.String("dest", "./generated", "destination directory root")
	mustParse(fs, args)

	srv := &api.Server{
		Reg:      a.reg,
		Engine:   a.engine,
		Resolver: a.resolver,
		Graph:    a.graph,
		Hook:     a.hook,
		Metrics:  a.metrics,
		DestRoot: *dest,
	}

	fmt.Printf("Serving Nerv API on %s (POST/GET /projects, GET /metrics, GET /healthz)\n", *addr)
	if err := http.ListenAndServe(*addr, srv.Router()); err != nil {
		log.Fatalf("nervctl serve: %v", err)
	}
}

func (a *app) cmdNew(args []string) {
	fs := newFlagSet("new")
	lang := fs.String("lang", "", "project language (required)")
	name := fs.String("name", "", "project name (required)")
	dest := fs.String("dest", "./generated", "destination directory root")
	deps := fs.String("deps", "", `comma-separated deps as name@version, e.g. "otel-sdk@1.4.2,grpc-go@1.60.1"`)
	mustParse(fs, args)

	if *lang == "" || *name == "" {
		log.Fatal("nervctl new: --lang and --name are required")
	}

	parsedDeps, err := parseDeps(*deps)
	if err != nil {
		log.Fatalf("nervctl new: parsing --deps: %v", err)
	}

	projectID := fmt.Sprintf("%s-%d", *name, time.Now().UnixNano())
	projectPath := filepath.Join(*dest, *name)

	// Validate + resolve dependencies BEFORE writing anything to disk —
	// a policy violation should abort generation, not produce a half-set-up
	// project with unpinned deps.
	if len(parsedDeps) > 0 {
		result, err := a.resolver.Resolve(projectID, parsedDeps)
		if err != nil {
			log.Fatalf("nervctl new: dependency resolution failed: %v", err)
		}
		a.metrics.RecordResolution(result.CacheHit)
		fmt.Printf("Resolved %d dependencies (cache hit: %v)\n", len(result.Resolved), result.CacheHit)
	}

	start := time.Now()
	err = a.engine.Render("service", projectPath, map[string]interface{}{"ServiceName": *name})
	if err != nil {
		log.Fatalf("nervctl new: rendering template: %v", err)
	}
	a.metrics.ObserveRenderDuration(time.Since(start).Seconds())

	pipelineRef, err := a.hook.TriggerPipeline(projectPath, *lang)
	if err != nil {
		log.Fatalf("nervctl new: wiring CI hook: %v", err)
	}

	err = a.reg.Register(registry.Project{
		ID:              projectID,
		Name:            *name,
		Language:        *lang,
		TemplateName:    "service",
		TemplateVersion: "v1",
		Path:            projectPath,
	})
	if err != nil {
		log.Fatalf("nervctl new: registering project: %v", err)
	}
	a.metrics.RecordProjectGenerated(*lang)

	fmt.Printf("Generated project %q (id=%s)\n  path:     %s\n  pipeline: %s\n", *name, projectID, projectPath, pipelineRef)
}

// parseDeps parses a comma-separated "name@version,name@version" string
// into depgraph.Dependency values. Empty input yields an empty (not nil)
// slice-safe result.
func parseDeps(raw string) ([]depgraph.Dependency, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return nil, nil
	}

	parts := strings.Split(raw, ",")
	deps := make([]depgraph.Dependency, 0, len(parts))
	for _, p := range parts {
		p = strings.TrimSpace(p)
		nameVer := strings.SplitN(p, "@", 2)
		if len(nameVer) != 2 || nameVer[0] == "" || nameVer[1] == "" {
			return nil, fmt.Errorf("invalid dep %q, want format name@version", p)
		}
		deps = append(deps, depgraph.Dependency{Name: nameVer[0], Constraint: nameVer[1]})
	}
	return deps, nil
}

func (a *app) cmdList(args []string) {
	fs := newFlagSet("list")
	lang := fs.String("lang", "", "filter by language (optional)")
	mustParse(fs, args)

	projects, err := a.reg.List(*lang)
	if err != nil {
		log.Fatalf("nervctl list: %v", err)
	}

	out, err := json.MarshalIndent(projects, "", "  ")
	if err != nil {
		log.Fatalf("nervctl list: marshaling: %v", err)
	}
	fmt.Println(string(out))
}

func (a *app) cmdServeMetrics(args []string) {
	fs := newFlagSet("serve-metrics")
	addr := fs.String("addr", ":9090", "listen address")
	mustParse(fs, args)

	http.Handle("/metrics", a.metrics.Handler())
	fmt.Printf("Serving metrics on %s/metrics\n", *addr)
	if err := http.ListenAndServe(*addr, nil); err != nil {
		log.Fatalf("nervctl serve-metrics: %v", err)
	}
}
