// Package cihook defines the interface Nerv uses to wire a newly
// registered project into CI/CD, plus a stub implementation that writes
// a pipeline config file to disk instead of calling a real CI system.
package cihook

import (
	"fmt"
	"os"
	"path/filepath"
)

// CIHook is called once per project registration to set up its pipeline.
type CIHook interface {
	// TriggerPipeline provisions CI/CD for a project at projectPath, in
	// the given language, and returns a human-readable reference to what
	// was set up (e.g. a file path or pipeline URL).
	TriggerPipeline(projectPath, language string) (string, error)
}

// StubHook writes a minimal pipeline YAML into the project directory
// instead of calling a real CI system. Swap for a GitLabHook or
// GitHubActionsHook later without touching callers.
type StubHook struct{}

func NewStubHook() *StubHook {
	return &StubHook{}
}

func (h *StubHook) TriggerPipeline(projectPath, language string) (string, error) {
	pipelinePath := filepath.Join(projectPath, ".nerv-pipeline.yaml")

	content := fmt.Sprintf(`# Auto-generated by Nerv cihook stub — replace with a real CI config.
language: %s
stages:
  - build
  - test
  - deploy
`, language)

	if err := os.MkdirAll(projectPath, 0o755); err != nil {
		return "", fmt.Errorf("cihook: creating project dir %q: %w", projectPath, err)
	}
	if err := os.WriteFile(pipelinePath, []byte(content), 0o644); err != nil {
		return "", fmt.Errorf("cihook: writing pipeline stub %q: %w", pipelinePath, err)
	}

	return pipelinePath, nil
}
